Extract test code (#21)
* Initial code for extracting test names and code from test modules

This works for the Annalyns Infiltration case, but could use some tidy
up and testing and suchlike.

It makes some assumptions about the shape of the code, that we would
need to either encforce by conventions, or remove.

* Rename functions

* Add deadEndsToString

The one is Parser doesn't do anything

* Add tests

* Remove transpiled file

* Replace process.stdin.fd by 0 because of errors

I observed weird errors saying:

> Error: EAGAIN: resource temporarily unavailable

And apparently, it has to do with the `process.stdin.fd` getter
according to this SO answer:
https://stackoverflow.com/questions/40362369/stdin-read-fails-on-some-input

So I just replaced it with 0.

* Simplify Main.elm

* Swap SingleTest and MultipleTests names

* Fix tests descriptions

* Fix forgotten port rename on JS side

* Update elm-test-rs to v1.1 with task_id

* Output extracted test code as json

* Add build of extract-test-code to container

* Add a step to extract test code in run.sh

* Modify run.sh to merge test code with jq

* Reactivate 'set -e' earlier in run.sh

* Fix tests order in merged results.json

* Fix the fix

* Fix forgotten version: 2 in error case

Co-authored-by: Matthieu Pizenberg <matthieu.pizenberg@gmail.com>