Replace process.stdin.fd by 0 because of errors
I observed weird errors saying:

> Error: EAGAIN: resource temporarily unavailable

And apparently, it has to do with the `process.stdin.fd` getter
according to this SO answer:
https://stackoverflow.com/questions/40362369/stdin-read-fails-on-some-input

So I just replaced it with 0.